//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17626
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebServices.BeginEndHcpcsService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HCPCS", Namespace="http://www.restfulwebservices.net/DataContracts/2008/01")]
    [System.SerializableAttribute()]
    public partial class HCPCS : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ActionCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ActionEffDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AnestBaseUnitsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ASCPayGrpField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ASCPayGrpEffDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BetosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CIM1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CIM2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CIM3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeAddDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CoverageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FillerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HcpcField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LabCert1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LabCert2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LabCert3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LabCert4Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LabCert5Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LabCert6Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LabCert7Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LabCert8Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LongDescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MCM1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MCM2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MCM3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MOGEffDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MOGPayGrpField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MOGPayIndField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MpiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PI1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PI2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PI3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PI4Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProcNoteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RicField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SeqNumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ShortDescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatuteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TermDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TOS1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TOS2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TOS3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TOS4Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TOS5Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string XRef1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string XRef2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string XRef3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string XRef4Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string XRef5Field;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ActionCode {
            get {
                return this.ActionCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ActionCodeField, value) != true)) {
                    this.ActionCodeField = value;
                    this.RaisePropertyChanged("ActionCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ActionEffDate {
            get {
                return this.ActionEffDateField;
            }
            set {
                if ((object.ReferenceEquals(this.ActionEffDateField, value) != true)) {
                    this.ActionEffDateField = value;
                    this.RaisePropertyChanged("ActionEffDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AnestBaseUnits {
            get {
                return this.AnestBaseUnitsField;
            }
            set {
                if ((object.ReferenceEquals(this.AnestBaseUnitsField, value) != true)) {
                    this.AnestBaseUnitsField = value;
                    this.RaisePropertyChanged("AnestBaseUnits");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string ASCPayGrp {
            get {
                return this.ASCPayGrpField;
            }
            set {
                if ((object.ReferenceEquals(this.ASCPayGrpField, value) != true)) {
                    this.ASCPayGrpField = value;
                    this.RaisePropertyChanged("ASCPayGrp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public string ASCPayGrpEffDate {
            get {
                return this.ASCPayGrpEffDateField;
            }
            set {
                if ((object.ReferenceEquals(this.ASCPayGrpEffDateField, value) != true)) {
                    this.ASCPayGrpEffDateField = value;
                    this.RaisePropertyChanged("ASCPayGrpEffDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public string Betos {
            get {
                return this.BetosField;
            }
            set {
                if ((object.ReferenceEquals(this.BetosField, value) != true)) {
                    this.BetosField = value;
                    this.RaisePropertyChanged("Betos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public string CIM1 {
            get {
                return this.CIM1Field;
            }
            set {
                if ((object.ReferenceEquals(this.CIM1Field, value) != true)) {
                    this.CIM1Field = value;
                    this.RaisePropertyChanged("CIM1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public string CIM2 {
            get {
                return this.CIM2Field;
            }
            set {
                if ((object.ReferenceEquals(this.CIM2Field, value) != true)) {
                    this.CIM2Field = value;
                    this.RaisePropertyChanged("CIM2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public string CIM3 {
            get {
                return this.CIM3Field;
            }
            set {
                if ((object.ReferenceEquals(this.CIM3Field, value) != true)) {
                    this.CIM3Field = value;
                    this.RaisePropertyChanged("CIM3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public string CodeAddDate {
            get {
                return this.CodeAddDateField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeAddDateField, value) != true)) {
                    this.CodeAddDateField = value;
                    this.RaisePropertyChanged("CodeAddDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=10)]
        public string Coverage {
            get {
                return this.CoverageField;
            }
            set {
                if ((object.ReferenceEquals(this.CoverageField, value) != true)) {
                    this.CoverageField = value;
                    this.RaisePropertyChanged("Coverage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=11)]
        public string Filler {
            get {
                return this.FillerField;
            }
            set {
                if ((object.ReferenceEquals(this.FillerField, value) != true)) {
                    this.FillerField = value;
                    this.RaisePropertyChanged("Filler");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=12)]
        public string Hcpc {
            get {
                return this.HcpcField;
            }
            set {
                if ((object.ReferenceEquals(this.HcpcField, value) != true)) {
                    this.HcpcField = value;
                    this.RaisePropertyChanged("Hcpc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=13)]
        public string LabCert1 {
            get {
                return this.LabCert1Field;
            }
            set {
                if ((object.ReferenceEquals(this.LabCert1Field, value) != true)) {
                    this.LabCert1Field = value;
                    this.RaisePropertyChanged("LabCert1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=14)]
        public string LabCert2 {
            get {
                return this.LabCert2Field;
            }
            set {
                if ((object.ReferenceEquals(this.LabCert2Field, value) != true)) {
                    this.LabCert2Field = value;
                    this.RaisePropertyChanged("LabCert2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=15)]
        public string LabCert3 {
            get {
                return this.LabCert3Field;
            }
            set {
                if ((object.ReferenceEquals(this.LabCert3Field, value) != true)) {
                    this.LabCert3Field = value;
                    this.RaisePropertyChanged("LabCert3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=16)]
        public string LabCert4 {
            get {
                return this.LabCert4Field;
            }
            set {
                if ((object.ReferenceEquals(this.LabCert4Field, value) != true)) {
                    this.LabCert4Field = value;
                    this.RaisePropertyChanged("LabCert4");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=17)]
        public string LabCert5 {
            get {
                return this.LabCert5Field;
            }
            set {
                if ((object.ReferenceEquals(this.LabCert5Field, value) != true)) {
                    this.LabCert5Field = value;
                    this.RaisePropertyChanged("LabCert5");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=18)]
        public string LabCert6 {
            get {
                return this.LabCert6Field;
            }
            set {
                if ((object.ReferenceEquals(this.LabCert6Field, value) != true)) {
                    this.LabCert6Field = value;
                    this.RaisePropertyChanged("LabCert6");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=19)]
        public string LabCert7 {
            get {
                return this.LabCert7Field;
            }
            set {
                if ((object.ReferenceEquals(this.LabCert7Field, value) != true)) {
                    this.LabCert7Field = value;
                    this.RaisePropertyChanged("LabCert7");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=20)]
        public string LabCert8 {
            get {
                return this.LabCert8Field;
            }
            set {
                if ((object.ReferenceEquals(this.LabCert8Field, value) != true)) {
                    this.LabCert8Field = value;
                    this.RaisePropertyChanged("LabCert8");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=21)]
        public string LongDescription {
            get {
                return this.LongDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.LongDescriptionField, value) != true)) {
                    this.LongDescriptionField = value;
                    this.RaisePropertyChanged("LongDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=22)]
        public string MCM1 {
            get {
                return this.MCM1Field;
            }
            set {
                if ((object.ReferenceEquals(this.MCM1Field, value) != true)) {
                    this.MCM1Field = value;
                    this.RaisePropertyChanged("MCM1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=23)]
        public string MCM2 {
            get {
                return this.MCM2Field;
            }
            set {
                if ((object.ReferenceEquals(this.MCM2Field, value) != true)) {
                    this.MCM2Field = value;
                    this.RaisePropertyChanged("MCM2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=24)]
        public string MCM3 {
            get {
                return this.MCM3Field;
            }
            set {
                if ((object.ReferenceEquals(this.MCM3Field, value) != true)) {
                    this.MCM3Field = value;
                    this.RaisePropertyChanged("MCM3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=25)]
        public string MOGEffDate {
            get {
                return this.MOGEffDateField;
            }
            set {
                if ((object.ReferenceEquals(this.MOGEffDateField, value) != true)) {
                    this.MOGEffDateField = value;
                    this.RaisePropertyChanged("MOGEffDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=26)]
        public string MOGPayGrp {
            get {
                return this.MOGPayGrpField;
            }
            set {
                if ((object.ReferenceEquals(this.MOGPayGrpField, value) != true)) {
                    this.MOGPayGrpField = value;
                    this.RaisePropertyChanged("MOGPayGrp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=27)]
        public string MOGPayInd {
            get {
                return this.MOGPayIndField;
            }
            set {
                if ((object.ReferenceEquals(this.MOGPayIndField, value) != true)) {
                    this.MOGPayIndField = value;
                    this.RaisePropertyChanged("MOGPayInd");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=28)]
        public string Mpi {
            get {
                return this.MpiField;
            }
            set {
                if ((object.ReferenceEquals(this.MpiField, value) != true)) {
                    this.MpiField = value;
                    this.RaisePropertyChanged("Mpi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=29)]
        public string PI1 {
            get {
                return this.PI1Field;
            }
            set {
                if ((object.ReferenceEquals(this.PI1Field, value) != true)) {
                    this.PI1Field = value;
                    this.RaisePropertyChanged("PI1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=30)]
        public string PI2 {
            get {
                return this.PI2Field;
            }
            set {
                if ((object.ReferenceEquals(this.PI2Field, value) != true)) {
                    this.PI2Field = value;
                    this.RaisePropertyChanged("PI2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=31)]
        public string PI3 {
            get {
                return this.PI3Field;
            }
            set {
                if ((object.ReferenceEquals(this.PI3Field, value) != true)) {
                    this.PI3Field = value;
                    this.RaisePropertyChanged("PI3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=32)]
        public string PI4 {
            get {
                return this.PI4Field;
            }
            set {
                if ((object.ReferenceEquals(this.PI4Field, value) != true)) {
                    this.PI4Field = value;
                    this.RaisePropertyChanged("PI4");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=33)]
        public string ProcNote {
            get {
                return this.ProcNoteField;
            }
            set {
                if ((object.ReferenceEquals(this.ProcNoteField, value) != true)) {
                    this.ProcNoteField = value;
                    this.RaisePropertyChanged("ProcNote");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=34)]
        public string Ric {
            get {
                return this.RicField;
            }
            set {
                if ((object.ReferenceEquals(this.RicField, value) != true)) {
                    this.RicField = value;
                    this.RaisePropertyChanged("Ric");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=35)]
        public string SeqNum {
            get {
                return this.SeqNumField;
            }
            set {
                if ((object.ReferenceEquals(this.SeqNumField, value) != true)) {
                    this.SeqNumField = value;
                    this.RaisePropertyChanged("SeqNum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=36)]
        public string ShortDescription {
            get {
                return this.ShortDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.ShortDescriptionField, value) != true)) {
                    this.ShortDescriptionField = value;
                    this.RaisePropertyChanged("ShortDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=37)]
        public string Statute {
            get {
                return this.StatuteField;
            }
            set {
                if ((object.ReferenceEquals(this.StatuteField, value) != true)) {
                    this.StatuteField = value;
                    this.RaisePropertyChanged("Statute");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=38)]
        public string TermDate {
            get {
                return this.TermDateField;
            }
            set {
                if ((object.ReferenceEquals(this.TermDateField, value) != true)) {
                    this.TermDateField = value;
                    this.RaisePropertyChanged("TermDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=39)]
        public string TOS1 {
            get {
                return this.TOS1Field;
            }
            set {
                if ((object.ReferenceEquals(this.TOS1Field, value) != true)) {
                    this.TOS1Field = value;
                    this.RaisePropertyChanged("TOS1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=40)]
        public string TOS2 {
            get {
                return this.TOS2Field;
            }
            set {
                if ((object.ReferenceEquals(this.TOS2Field, value) != true)) {
                    this.TOS2Field = value;
                    this.RaisePropertyChanged("TOS2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=41)]
        public string TOS3 {
            get {
                return this.TOS3Field;
            }
            set {
                if ((object.ReferenceEquals(this.TOS3Field, value) != true)) {
                    this.TOS3Field = value;
                    this.RaisePropertyChanged("TOS3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=42)]
        public string TOS4 {
            get {
                return this.TOS4Field;
            }
            set {
                if ((object.ReferenceEquals(this.TOS4Field, value) != true)) {
                    this.TOS4Field = value;
                    this.RaisePropertyChanged("TOS4");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=43)]
        public string TOS5 {
            get {
                return this.TOS5Field;
            }
            set {
                if ((object.ReferenceEquals(this.TOS5Field, value) != true)) {
                    this.TOS5Field = value;
                    this.RaisePropertyChanged("TOS5");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=44)]
        public string XRef1 {
            get {
                return this.XRef1Field;
            }
            set {
                if ((object.ReferenceEquals(this.XRef1Field, value) != true)) {
                    this.XRef1Field = value;
                    this.RaisePropertyChanged("XRef1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=45)]
        public string XRef2 {
            get {
                return this.XRef2Field;
            }
            set {
                if ((object.ReferenceEquals(this.XRef2Field, value) != true)) {
                    this.XRef2Field = value;
                    this.RaisePropertyChanged("XRef2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=46)]
        public string XRef3 {
            get {
                return this.XRef3Field;
            }
            set {
                if ((object.ReferenceEquals(this.XRef3Field, value) != true)) {
                    this.XRef3Field = value;
                    this.RaisePropertyChanged("XRef3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=47)]
        public string XRef4 {
            get {
                return this.XRef4Field;
            }
            set {
                if ((object.ReferenceEquals(this.XRef4Field, value) != true)) {
                    this.XRef4Field = value;
                    this.RaisePropertyChanged("XRef4");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=48)]
        public string XRef5 {
            get {
                return this.XRef5Field;
            }
            set {
                if ((object.ReferenceEquals(this.XRef5Field, value) != true)) {
                    this.XRef5Field = value;
                    this.RaisePropertyChanged("XRef5");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DefaultFaultContract", Namespace="http://GOTLServices.FaultContracts/2008/01")]
    [System.SerializableAttribute()]
    public partial class DefaultFaultContract : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int ErrorIdField;
        
        private string ErrorMessageField;
        
        private System.Guid CorrelationIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ErrorId {
            get {
                return this.ErrorIdField;
            }
            set {
                if ((this.ErrorIdField.Equals(value) != true)) {
                    this.ErrorIdField = value;
                    this.RaisePropertyChanged("ErrorId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string ErrorMessage {
            get {
                return this.ErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMessageField, value) != true)) {
                    this.ErrorMessageField = value;
                    this.RaisePropertyChanged("ErrorMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public System.Guid CorrelationId {
            get {
                return this.CorrelationIdField;
            }
            set {
                if ((this.CorrelationIdField.Equals(value) != true)) {
                    this.CorrelationIdField = value;
                    this.RaisePropertyChanged("CorrelationId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.restfulwebservices.net/ServiceContracts/2008/01", ConfigurationName="BeginEndHcpcsService.IHCPCSService")]
    public interface IHCPCSService {
        
        [System.ServiceModel.OperationContractAttribute(Action="GetDetailsByCode", ReplyAction="http://www.restfulwebservices.net/ServiceContracts/2008/01/IHCPCSService/GetDetai" +
            "lsByCodeResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WebServices.BeginEndHcpcsService.DefaultFaultContract), Action="http://www.restfulwebservices.net/ServiceContracts/2008/01/IHCPCSService/GetDetai" +
            "lsByCodeDefaultFaultContractFault", Name="DefaultFaultContract", Namespace="http://GOTLServices.FaultContracts/2008/01")]
        WebServices.BeginEndHcpcsService.HCPCS GetDetailsByCode(string request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="GetDetailsByCode", ReplyAction="http://www.restfulwebservices.net/ServiceContracts/2008/01/IHCPCSService/GetDetai" +
            "lsByCodeResponse")]
        System.IAsyncResult BeginGetDetailsByCode(string request, System.AsyncCallback callback, object asyncState);
        
        WebServices.BeginEndHcpcsService.HCPCS EndGetDetailsByCode(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="GetDetailsByDescription", ReplyAction="http://www.restfulwebservices.net/ServiceContracts/2008/01/IHCPCSService/GetDetai" +
            "lsByDescriptionResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WebServices.BeginEndHcpcsService.DefaultFaultContract), Action="http://www.restfulwebservices.net/ServiceContracts/2008/01/IHCPCSService/GetDetai" +
            "lsByDescriptionDefaultFaultContractFault", Name="DefaultFaultContract", Namespace="http://GOTLServices.FaultContracts/2008/01")]
        WebServices.BeginEndHcpcsService.HCPCS[] GetDetailsByDescription(string request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="GetDetailsByDescription", ReplyAction="http://www.restfulwebservices.net/ServiceContracts/2008/01/IHCPCSService/GetDetai" +
            "lsByDescriptionResponse")]
        System.IAsyncResult BeginGetDetailsByDescription(string request, System.AsyncCallback callback, object asyncState);
        
        WebServices.BeginEndHcpcsService.HCPCS[] EndGetDetailsByDescription(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="GetDetailsBySeqNmber", ReplyAction="http://www.restfulwebservices.net/ServiceContracts/2008/01/IHCPCSService/GetDetai" +
            "lsBySeqNmberResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WebServices.BeginEndHcpcsService.DefaultFaultContract), Action="http://www.restfulwebservices.net/ServiceContracts/2008/01/IHCPCSService/GetDetai" +
            "lsBySeqNmberDefaultFaultContractFault", Name="DefaultFaultContract", Namespace="http://GOTLServices.FaultContracts/2008/01")]
        WebServices.BeginEndHcpcsService.HCPCS GetDetailsBySeqNmber(string request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="GetDetailsBySeqNmber", ReplyAction="http://www.restfulwebservices.net/ServiceContracts/2008/01/IHCPCSService/GetDetai" +
            "lsBySeqNmberResponse")]
        System.IAsyncResult BeginGetDetailsBySeqNmber(string request, System.AsyncCallback callback, object asyncState);
        
        WebServices.BeginEndHcpcsService.HCPCS EndGetDetailsBySeqNmber(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IHCPCSServiceChannel : WebServices.BeginEndHcpcsService.IHCPCSService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetDetailsByCodeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetDetailsByCodeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public WebServices.BeginEndHcpcsService.HCPCS Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((WebServices.BeginEndHcpcsService.HCPCS)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetDetailsByDescriptionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetDetailsByDescriptionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public WebServices.BeginEndHcpcsService.HCPCS[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((WebServices.BeginEndHcpcsService.HCPCS[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetDetailsBySeqNmberCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetDetailsBySeqNmberCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public WebServices.BeginEndHcpcsService.HCPCS Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((WebServices.BeginEndHcpcsService.HCPCS)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HCPCSServiceClient : System.ServiceModel.ClientBase<WebServices.BeginEndHcpcsService.IHCPCSService>, WebServices.BeginEndHcpcsService.IHCPCSService {
        
        private BeginOperationDelegate onBeginGetDetailsByCodeDelegate;
        
        private EndOperationDelegate onEndGetDetailsByCodeDelegate;
        
        private System.Threading.SendOrPostCallback onGetDetailsByCodeCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetDetailsByDescriptionDelegate;
        
        private EndOperationDelegate onEndGetDetailsByDescriptionDelegate;
        
        private System.Threading.SendOrPostCallback onGetDetailsByDescriptionCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetDetailsBySeqNmberDelegate;
        
        private EndOperationDelegate onEndGetDetailsBySeqNmberDelegate;
        
        private System.Threading.SendOrPostCallback onGetDetailsBySeqNmberCompletedDelegate;
        
        public HCPCSServiceClient() {
        }
        
        public HCPCSServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HCPCSServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HCPCSServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HCPCSServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<GetDetailsByCodeCompletedEventArgs> GetDetailsByCodeCompleted;
        
        public event System.EventHandler<GetDetailsByDescriptionCompletedEventArgs> GetDetailsByDescriptionCompleted;
        
        public event System.EventHandler<GetDetailsBySeqNmberCompletedEventArgs> GetDetailsBySeqNmberCompleted;
        
        public WebServices.BeginEndHcpcsService.HCPCS GetDetailsByCode(string request) {
            return base.Channel.GetDetailsByCode(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginGetDetailsByCode(string request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetDetailsByCode(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public WebServices.BeginEndHcpcsService.HCPCS EndGetDetailsByCode(System.IAsyncResult result) {
            return base.Channel.EndGetDetailsByCode(result);
        }
        
        private System.IAsyncResult OnBeginGetDetailsByCode(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string request = ((string)(inValues[0]));
            return this.BeginGetDetailsByCode(request, callback, asyncState);
        }
        
        private object[] OnEndGetDetailsByCode(System.IAsyncResult result) {
            WebServices.BeginEndHcpcsService.HCPCS retVal = this.EndGetDetailsByCode(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetDetailsByCodeCompleted(object state) {
            if ((this.GetDetailsByCodeCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetDetailsByCodeCompleted(this, new GetDetailsByCodeCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetDetailsByCodeAsync(string request) {
            this.GetDetailsByCodeAsync(request, null);
        }
        
        public void GetDetailsByCodeAsync(string request, object userState) {
            if ((this.onBeginGetDetailsByCodeDelegate == null)) {
                this.onBeginGetDetailsByCodeDelegate = new BeginOperationDelegate(this.OnBeginGetDetailsByCode);
            }
            if ((this.onEndGetDetailsByCodeDelegate == null)) {
                this.onEndGetDetailsByCodeDelegate = new EndOperationDelegate(this.OnEndGetDetailsByCode);
            }
            if ((this.onGetDetailsByCodeCompletedDelegate == null)) {
                this.onGetDetailsByCodeCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetDetailsByCodeCompleted);
            }
            base.InvokeAsync(this.onBeginGetDetailsByCodeDelegate, new object[] {
                        request}, this.onEndGetDetailsByCodeDelegate, this.onGetDetailsByCodeCompletedDelegate, userState);
        }
        
        public WebServices.BeginEndHcpcsService.HCPCS[] GetDetailsByDescription(string request) {
            return base.Channel.GetDetailsByDescription(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginGetDetailsByDescription(string request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetDetailsByDescription(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public WebServices.BeginEndHcpcsService.HCPCS[] EndGetDetailsByDescription(System.IAsyncResult result) {
            return base.Channel.EndGetDetailsByDescription(result);
        }
        
        private System.IAsyncResult OnBeginGetDetailsByDescription(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string request = ((string)(inValues[0]));
            return this.BeginGetDetailsByDescription(request, callback, asyncState);
        }
        
        private object[] OnEndGetDetailsByDescription(System.IAsyncResult result) {
            WebServices.BeginEndHcpcsService.HCPCS[] retVal = this.EndGetDetailsByDescription(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetDetailsByDescriptionCompleted(object state) {
            if ((this.GetDetailsByDescriptionCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetDetailsByDescriptionCompleted(this, new GetDetailsByDescriptionCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetDetailsByDescriptionAsync(string request) {
            this.GetDetailsByDescriptionAsync(request, null);
        }
        
        public void GetDetailsByDescriptionAsync(string request, object userState) {
            if ((this.onBeginGetDetailsByDescriptionDelegate == null)) {
                this.onBeginGetDetailsByDescriptionDelegate = new BeginOperationDelegate(this.OnBeginGetDetailsByDescription);
            }
            if ((this.onEndGetDetailsByDescriptionDelegate == null)) {
                this.onEndGetDetailsByDescriptionDelegate = new EndOperationDelegate(this.OnEndGetDetailsByDescription);
            }
            if ((this.onGetDetailsByDescriptionCompletedDelegate == null)) {
                this.onGetDetailsByDescriptionCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetDetailsByDescriptionCompleted);
            }
            base.InvokeAsync(this.onBeginGetDetailsByDescriptionDelegate, new object[] {
                        request}, this.onEndGetDetailsByDescriptionDelegate, this.onGetDetailsByDescriptionCompletedDelegate, userState);
        }
        
        public WebServices.BeginEndHcpcsService.HCPCS GetDetailsBySeqNmber(string request) {
            return base.Channel.GetDetailsBySeqNmber(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginGetDetailsBySeqNmber(string request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetDetailsBySeqNmber(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public WebServices.BeginEndHcpcsService.HCPCS EndGetDetailsBySeqNmber(System.IAsyncResult result) {
            return base.Channel.EndGetDetailsBySeqNmber(result);
        }
        
        private System.IAsyncResult OnBeginGetDetailsBySeqNmber(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string request = ((string)(inValues[0]));
            return this.BeginGetDetailsBySeqNmber(request, callback, asyncState);
        }
        
        private object[] OnEndGetDetailsBySeqNmber(System.IAsyncResult result) {
            WebServices.BeginEndHcpcsService.HCPCS retVal = this.EndGetDetailsBySeqNmber(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetDetailsBySeqNmberCompleted(object state) {
            if ((this.GetDetailsBySeqNmberCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetDetailsBySeqNmberCompleted(this, new GetDetailsBySeqNmberCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetDetailsBySeqNmberAsync(string request) {
            this.GetDetailsBySeqNmberAsync(request, null);
        }
        
        public void GetDetailsBySeqNmberAsync(string request, object userState) {
            if ((this.onBeginGetDetailsBySeqNmberDelegate == null)) {
                this.onBeginGetDetailsBySeqNmberDelegate = new BeginOperationDelegate(this.OnBeginGetDetailsBySeqNmber);
            }
            if ((this.onEndGetDetailsBySeqNmberDelegate == null)) {
                this.onEndGetDetailsBySeqNmberDelegate = new EndOperationDelegate(this.OnEndGetDetailsBySeqNmber);
            }
            if ((this.onGetDetailsBySeqNmberCompletedDelegate == null)) {
                this.onGetDetailsBySeqNmberCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetDetailsBySeqNmberCompleted);
            }
            base.InvokeAsync(this.onBeginGetDetailsBySeqNmberDelegate, new object[] {
                        request}, this.onEndGetDetailsBySeqNmberDelegate, this.onGetDetailsBySeqNmberCompletedDelegate, userState);
        }
    }
}
